name: Grip Build and Release

on:
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build Grip
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        rust: [1.34.0, nightly]
        build_type: [Debug, Release]
      fail-fast: false

    env:
      PKG_CONFIG_ALLOW_CROSS: 1
      TARGET: i686-unknown-linux-gnu
      CXX: /usr/bin/clang++-8
      CC: /usr/bin/clang-8

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Linux Dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y \
            libssl-dev:i386 lib32stdc++6 lib32z1-dev libc6-dev-i386 \
            gcc-multilib g++-multilib ninja-build clang-8 lld-8 cmake

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: i686-unknown-linux-gnu
          override: true

      - name: Install cargo-sweep
        run: cargo install cargo-sweep || true

      - name: Show Compiler Version
        run: $CXX --version

      - name: Prepare Build Directories
        run: |
          mkdir -p build/${{ matrix.build_type | toLower }}/rust
          mkdir -p build/${{ matrix.build_type | toLower }}

      - name: Build Rust code
        working-directory: rust
        run: |
          CARGO_TARGET_DIR=${GITHUB_WORKSPACE}/build/${{ matrix.build_type | toLower }}/rust \
          cargo build --verbose --target $TARGET ${{ matrix.build_type == 'Release' && '--release' || '' }}

      - name: Build CMake project
        working-directory: build/${{ matrix.build_type | toLower }}
        run: |
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          make -j$(nproc)

      - name: Prepare deploy artifacts
        if: matrix.build_type == 'Release' && matrix.rust == '1.34.0'
        run: |
          mkdir -p deploy/addons/amxmodx/modules
          mkdir -p deploy/addons/amxmodx/configs
          mkdir -p deploy/addons/amxmodx/scripting/include
          cp build/release/*.so deploy/addons/amxmodx/modules
          strip --strip-debug deploy/addons/amxmodx/modules/*.so
          cp configs/* deploy/addons/amxmodx/configs
          cp scripting/* deploy/addons/amxmodx/scripting/include

      - name: Create tar.gz
        if: matrix.build_type == 'Release' && matrix.rust == '1.34.0'
        working-directory: deploy
        run: |
          tar czf ../grip-${GITHUB_REF##*/}-${TARGET}.tar.gz addons

      - name: Upload artifacts
        if: matrix.build_type == 'Release' && matrix.rust == '1.34.0'
        uses: actions/upload-artifact@v4
        with:
          name: grip-${{ github.ref_name }}-${{ env.TARGET }}
          path: grip-${{ github.ref_name }}-${{ env.TARGET }}.tar.gz
