name: Build and Upload

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest]
        rust: [1.34.0, nightly]
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies (Linux only)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libssl-dev:i386 lib32stdc++6 lib32z1-dev libc6-dev-i386 \
          gcc-multilib g++-multilib ninja-build clang-8 lld-8 cmake

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        target: i686-unknown-linux-gnu
        override: true

    - name: Build project
      run: |
        mkdir -p build
        cargo build --verbose --release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.os }}-${{ matrix.rust }}
        path: |
          target/release/
